name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build -- --configuration production

      - name: Run Tests
        run: |
          npm install --no-save karma karma-cli karma-chrome-launcher karma-coverage
          npm test -- --watch=false --browsers=ChromeHeadless

      - name: Run Security Audit
        run: npm audit --audit-level=moderate || true

      - name: Check for Angular Updates
        run: npx ng update --force

      - name: Check and Apply Other Package Updates
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install

      - name: Commit and Push Updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: auto-update dependencies [CI]" || echo "No changes"
          git push || echo "No push (maybe no permission or protected branch)"
